name: Run Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.12'
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.1.13
      - name: Install dependencies
        shell: bash
        run: |
          python -m poetry install
      - name: Test
        run: |
          python -m poetry run python -m unittest tests/test_push_gateway_pruner.py